management:
  health:
    defaults:
      enabled: true
    web:
      exposure:
        include: "*"
#  security:
#    enabled: false
server:
  port: 9090
  ip: 1.2.3.4
spring:
  application:
    name: Mini-Cars-Inc
  datasource:
    url: jdbc:mysql://localhost:3306/sys
    userName: tacos
    password: password123
#logging:
#  level: DEBUG
#  org.springframework.security: DEBUG
logging:
  pattern:
    console: "%d{HH:mm:ss.SSS} %-5level %logger{36} - %msg%n"
    file: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
  level:
      org.springframework.web: DEBUG
      com.genil.learning.minisocialsvc: DEBUG
  file: app.log

okta:
  oauth2:
    client-id: 0oa2c5c157yzmUq6u357
    issuer: https://dev-405161.okta.com/oauth2/default
info:
  app:
    name: Mini Cars Inc Spring Boot Application
    description: Mini Cars Inc is a privately owned organization.
    version: Curious? Really !
  helpline:
    email: admin@antony.com
    phone: 0120-32-5252
enable:
  swagger: true
wordpress:
  menus:
    - title: Home
      name: Home
      path: /
    - title: About
      name: About
      path: /about
  themes:
    default-folder: /wp-content/themes/triedthemes
  servers:
    - ip: 127.0.0.1
      path: /dev1
    - ip: 127.0.0.2
      path: /dev2
    - ip: 127.0.0.3
      path: /dev3

transport:
  countries:
    - name: India
      mode: Road
      common: Bus
    - name: USA
      mode: Sky
      common: flight
  music:
    default-folder: Rahman