endpoints:
  health:
    enabled: false
server:
  ip: 5.7.8.10
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/healthapp
    userName: developer
    password: Thirra1401!
#logging:
#  level: DEBUG
#  org.springframework.security: DEBUG
okta:
  oauth2:
    client-id: 0oa2c5c157yzmUq6u357
    issuer: https://dev-405161.okta.com/oauth2/default